version: '3'
services:
  dev:
    #image: codehammers/ch-dev:latest
    #image: codehammers/ch-dev-dep-v2:latest
    #image: codehammers/ch-tracker-dev:latest
    image: codehammers/ch-dev-dep-v3:latest
    container_name: ch-dev
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - client_node_modules:/usr/src/app/client/node_modules
    command: npm run dev-ts
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://codehammers:ch-dev@postgres:5432/ch-dev-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ch-dev
      - POSTGRES_DB=ch-dev-database
      - AWS_ACCESS_KEY_ID=placeholder-value
      - AWS_SECRET_ACCESS_KEY=placeholder-value
      - AWS_REGION=placeholder-value
      - BUCKET_NAME=placeholder-value
      # suppress aws sdk v2 deprecation warning
      - AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1;
    depends_on:
      - postgres
  postgres:
    image: codehammers/postgres-dev:latest
    container_name: codehammers-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ch-dev-database
      - POSTGRES_PASSWORD=ch-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  node_modules:
  client_node_modules:
  postgres-data:
