version: '3'

services:
  test:
    #image: codehammers/ch-tracker-dev:latest
    image: codehammers/ch-dev-dep-v3:latest
    container_name: ch-test
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - client_node_modules:/usr/src/app/client/node_modules
    depends_on:
      - mongo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://mongo:27017/ch-testdb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ch-dev-database
      - POSTGRES_PASSWORD=ch-dev
      - AWS_ACCESS_KEY_ID=placeholder-value
      - AWS_SECRET_ACCESS_KEY=placeholder-value
      - AWS_REGION=placeholder-value
      - BUCKET_NAME=placeholder-value
      # suppress aws sdk v2 deprecation warning
      - AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1;
    command: npm run test:all

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=ch-testdb
    # mute mongo container logs
    command: mongod --quiet --logpath /dev/null

volumes:
  node_modules:
  client_node_modules:
  mongodata:
