version: "3"
services:
  dev:
    #image: codehammers/ch-dev:latest
    image: codehammers/ch-dev-dep-test:latest
    container_name: ch-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - client_node_modules:/usr/src/app/client/node_modules
    command: npm run dev-ts
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
  client_node_modules:
