version: "3"

services:
  test:
    image: codehammers/cd-testv1:latest
    container_name: ch-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/ch-testdb
      - JWT_SECRET=${JWT_SECRET}
    command: npm run test:all

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ch-testdb

volumes:
  node_modules:
  mongodata:
