services:
  dev:
    image: codehammers/ch-dev-dep-v2:latest
    container_name: ch-dev
    ports:
      - '8080:8080'
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
      - client_node_modules:/usr/src/app/client/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://root:rootPass@ch-mongo-dev:27017/ch-testdb
    depends_on:
      - ch-mongo-dev
    command: npm run dev-ts

  ch-mongo-dev:
    container_name: ch-mongo-dev
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ch-testdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_HOST=ch-mongo-dev
      - MONGO_USER=root
      - MONGO_USER_PWD=rootPass
    volumes:
      - ./scripts/db/mongo-dev-init/:/docker-entrypoint-initdb.d
      - mongo-dev-volume:/data/db
    command: mongod --quiet --logpath /dev/null
volumes:
  node_modules:
  client_node_modules:
  mongo-dev-volume:
