# Set Node version
FROM node:18.17.1

# Install webpack globally
RUN npm install webpack -g

# Set the working directory
WORKDIR /usr/src/app

# Copy both package.json files
COPY package.json .
COPY ./client/package.json ./client/

# Install root packages
RUN npm install

# Install client packages
RUN cd client && npm install

# Expose the webpack-dev-server port
EXPOSE 3000


