# Use the official Node.js 18 image as base
FROM node:18.17.1

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install root packages
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Navigate to the client directory and install client packages
WORKDIR /usr/src/app/client
COPY client/package*.json ./
RUN npm install

# Navigate back to the main app directory
WORKDIR /usr/src/app

ENTRYPOINT []

# Expose the port the app runs on
EXPOSE 3000



