version: "3"

services:
  test:
    image: brok3turtl3/codehammers:latest
    container_name: ch-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test:client

volumes:
  node_modules:
