name: build-tests
on:
  pull_request:
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t codehammers/cd-testv1:latest -f Dockerfile-dev .
      - name: Install Root Dependencies
        run: docker run codehammers/cd-testv1:latest npm install
      - name: Install Client Dependencies
        run: docker run codehammers/cd-testv1:latest /bin/sh -c "cd client && npm install"
      #- name: List node_modules
      #run: docker run codehammers/cd-testv1:latest /bin/sh -c "ls node_modules && cd client && ls node_modules"
      - run: docker-compose -f docker-compose-test.yml up --abort-on-container-exit
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
